[project]
name = "py-pip"
version = "2023.0.0"
requires-python = ">=3.8"
dependencies = ["httpx", "xdg", "tqdm"]

classifiers = ["Private :: Do Not Upload"]


[tool.pip-tools]
generate-hashes = true
resolver = "backtracking"
